# Generated by Django 4.0 on 2022-01-01 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SIMS_Admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staffroles',
            options={'verbose_name_plural': 'Staff Roles'},
        ),
        migrations.AlterModelOptions(
            name='studentroles',
            options={'verbose_name_plural': 'Student Roles'},
        ),
        migrations.RemoveField(
            model_name='staff',
            name='email',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='staffID',
        ),
        migrations.RemoveField(
            model_name='student',
            name='studentID',
        ),
    ]
