# Generated by Django 4.0 on 2022-01-03 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SIMS_Admin', '0002_alter_staffroles_options_alter_studentroles_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=50)),
                ('section', models.CharField(help_text='Eg- A,B,C etc', max_length=10)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Student Class',
                'db_table': 'Student Class',
            },
        ),
        migrations.RenameField(
            model_name='student',
            old_name='acct',
            new_name='student_reg',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='role',
            new_name='student_role',
        ),
        migrations.RemoveField(
            model_name='student',
            name='level',
        ),
        migrations.AddField(
            model_name='student',
            name='student_date_of_birth',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='student_gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=8, null=True),
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_title', models.CharField(db_index=True, max_length=14, unique=True)),
                ('subject_code', models.CharField(db_index=True, max_length=14, unique=True)),
                ('subject_creation_date', models.DateTimeField(auto_now_add=True)),
                ('level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SIMS_Admin.studentclass')),
            ],
            options={
                'verbose_name_plural': 'Subject Title',
            },
        ),
        migrations.CreateModel(
            name='SubjectCombination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('select_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SIMS_Admin.studentclass')),
                ('select_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SIMS_Admin.subjects')),
            ],
            options={
                'verbose_name_plural': 'Subject Combination',
            },
        ),
        migrations.AddField(
            model_name='student',
            name='student_class',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SIMS_Admin.studentclass'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SIMS_Admin.studentclass'),
        ),
        migrations.DeleteModel(
            name='Levels',
        ),
    ]
