# Generated by Django 4.0 on 2022-01-03 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIMS_Admin', '0003_studentclass_rename_acct_student_student_reg_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='student_reg',
            new_name='student_acct',
        ),
        migrations.AlterField(
            model_name='student',
            name='student_date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
