# Generated by Django 4.0 on 2022-01-03 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SIMS_Admin', '0004_rename_student_reg_student_student_acct_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subjects',
            options={'verbose_name_plural': 'Subjects'},
        ),
        migrations.RemoveField(
            model_name='subjects',
            name='level',
        ),
        migrations.AlterField(
            model_name='subjectcombination',
            name='select_class',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='SIMS_Admin.studentclass'),
        ),
    ]
