# Generated by Django 4.0 on 2022-01-03 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SIMS_Admin', '0005_alter_subjects_options_remove_subjects_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectcombination',
            name='combination_desc',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='subjectcombination',
            name='select_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SIMS_Admin.studentclass'),
        ),
    ]
