# Generated by Django 4.0 on 2022-01-03 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIMS_Admin', '0006_subjectcombination_combination_desc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentclass',
            name='class_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
