# Generated by Django 4.0 on 2022-01-03 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIMS_Admin', '0007_alter_studentclass_class_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentclass',
            name='class_name',
            field=models.CharField(max_length=50),
        ),
    ]
