# Generated by Django 4.0 on 2022-01-06 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SIMS_Authentication', '0003_alter_accounts_othername_alter_accounts_picture'),
        ('SIMS_Admin', '0008_alter_studentclass_class_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_acct',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_acct', to='SIMS_Authentication.accounts'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SIMS_Admin.studentclass'),
        ),
    ]
