# Generated by Django 4.0 on 2022-01-06 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SIMS_Admin', '0009_alter_student_student_acct_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='acct',
            new_name='staff_acct',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='level',
            new_name='staff_class',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='phone',
            new_name='staff_phone',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='role',
        ),
        migrations.AddField(
            model_name='staff',
            name='staff_date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='staff_gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='staff_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SIMS_Admin.staffroles'),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='subject_title',
            field=models.CharField(db_index=True, max_length=30, unique=True),
        ),
    ]
