# Generated by Django 4.0 on 2022-01-10 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SIMS_Admin', '0010_rename_acct_staff_staff_acct_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentGrades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_ca1', models.IntegerField(default=0)),
                ('student_ca2', models.IntegerField(default=0)),
                ('student_ca3', models.IntegerField(default=0)),
                ('student_exam', models.IntegerField(default=0)),
                ('student_total', models.IntegerField(default=0)),
                ('select_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SIMS_Admin.student')),
                ('select_subject', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='SIMS_Admin.subjects')),
            ],
            options={
                'verbose_name_plural': 'Student Grades',
            },
        ),
        migrations.CreateModel(
            name='StaffClassCombination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SIMS_Admin.studentclass')),
            ],
            options={
                'verbose_name_plural': 'Staff Assigned Class',
            },
        ),
    ]
