# Generated by Django 4.0 on 2022-01-10 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SIMS_Admin', '0011_studentgrades_staffclasscombination'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffclasscombination',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SIMS_Admin.staff'),
        ),
        migrations.AlterField(
            model_name='staffclasscombination',
            name='student_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SIMS_Admin.studentclass'),
        ),
        migrations.AlterField(
            model_name='studentgrades',
            name='select_student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SIMS_Admin.student'),
        ),
        migrations.AlterField(
            model_name='studentgrades',
            name='select_subject',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SIMS_Admin.subjects'),
        ),
    ]
