# Generated by Django 4.0 on 2022-01-10 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIMS_Admin', '0012_staffclasscombination_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffclasscombination',
            name='combination_desc',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
