# Generated by Django 4.0 on 2022-01-11 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SIMS_Admin', '0013_staffclasscombination_combination_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentgrades',
            name='slug',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='studentgrades',
            name='select_subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SIMS_Admin.subjects'),
        ),
    ]
