# Generated by Django 4.0 on 2022-01-11 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIMS_Admin', '0014_studentgrades_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentgrades',
            name='student_ca1',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='studentgrades',
            name='student_ca2',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='studentgrades',
            name='student_ca3',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='studentgrades',
            name='student_exam',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='studentgrades',
            name='student_total',
            field=models.IntegerField(),
        ),
    ]
