# Generated by Django 4.0 on 2022-01-11 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SIMS_Admin', '0015_alter_studentgrades_student_ca1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentgrades',
            name='select_subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SIMS_Admin.subjectcombination'),
        ),
    ]
