# Generated by Django 4.0 on 2022-01-13 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SIMS_Authentication', '0004_alter_accounts_picture'),
        ('SIMS_Admin', '0016_alter_studentgrades_select_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_phone', models.CharField(db_index=True, max_length=14, unique=True)),
                ('admin_gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=8, null=True)),
                ('admin_date_of_birth', models.DateField(blank=True, null=True)),
                ('admin_acct', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SIMS_Authentication.accounts')),
            ],
            options={
                'verbose_name_plural': 'Admins',
            },
        ),
    ]
