# Generated by Django 4.0 on 2021-12-30 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIMS_Authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accounts',
            options={'verbose_name_plural': 'Accounts'},
        ),
        migrations.RemoveField(
            model_name='accounts',
            name='username',
        ),
        migrations.AddField(
            model_name='accounts',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=50, unique=True, verbose_name='email address'),
        ),
        migrations.AddField(
            model_name='accounts',
            name='schNo',
            field=models.CharField(blank=True, db_index=True, max_length=30, unique=True),
        ),
    ]
