# Generated by Django 4.0 on 2022-01-01 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIMS_Authentication', '0002_alter_accounts_options_remove_accounts_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='othername',
            field=models.CharField(blank=True, db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='picture',
            field=models.ImageField(default='user.png', null=True, upload_to='uploaded/'),
        ),
    ]
